### ISSUE TITLE
Transfer information from Old Resources

### ISSUE THREAD

**Issue by trickeydan** [roboticsoutreach/kb#3]
- [x] https://github.com/sourcebots/wiki
- [x] https://github.com/sourcebots/volunteer-docs
- [ ] Information from Student Robotics Trac and similar
- [x] https://github.com/roboticsoutreach/smallpeice-runbook

**Comment by kierdavis** [comment]
There's a wealth of information in old student robotics repositories we could dig into too e.g. recurring-tasks.

**Comment by kierdavis** [comment]
Also, could the smallpeice runbook be merged into this repository too?

**Comment by trickeydan** [comment]
> There's a wealth of information in old student robotics repositories we could dig into too e.g. recurring-tasks.

> Also, could the smallpeice runbook be merged into this repository too?

Added both

**Comment by trickeydan** [comment]
All of the information from Trac was transferred to the SR runbook: https://studentrobotics.org/runbook
