### ISSUE TITLE
Netlify deploy is not working

### ISSUE THREAD

**Issue by trickeydan** [roboticsoutreach/kb#41]

**Comment by tpoomlmly** [comment]
`mkdocs-material-extensions` dropped support for python 2, which is what the Netlify system is configured to use at the moment

**Comment by tpoomlmly** [comment]
Another thing's gone and broken itself
- `jinja2.exceptions.TemplateNotFound: .icons/.svg`
- https://app.netlify.com/sites/sro/deploys/610b1675c621ce0007c19864
